### ISSUE TITLE
Can we merge GLB, batchtable, and featuretable into b3DM

### ISSUE THREAD

**Issue by jingyangking** [bertt/b3dm.tooling#1]
If I want to combine a glb file with batchtable and featuretable files to form a b3dm file with attribute values, what command should I write on the command line? What settings are required for the glb, batchtable, and featuretable files to merge? Thank you!

**Comment by bertt** [comment]
Pack option with glb as input, the tool searches  for batch/featuretable json

**Comment by jingyangking** [comment]
> Pack option with glb as input, the tool searches for batch/featuretable json

Does the absence of batchid in my original GLB file affect the generated b3DM

**Comment by bertt** [comment]
the tool takes the original glb file and packs it together with the json files. If the orginal glb does not the batchid vertex attribute then in 3D Tiles viewers the attributes can not be retrieved.

**Comment by jingyangking** [comment]
Thank you very much for your reply. If I have GLB, batchtable, and featuretable now, how can I import the corresponding batchtable and featuretable when synthesizing b3mm through GLB? Like this: $b3mm pack - i 1. glb - c batchtable.json - p featuretable?

**Comment by bertt** [comment]
$b3dm pack - i 1. glb is enough

**Comment by jingyangking** [comment]
Okay, thank you. I think I know what to do now.
