### ISSUE TITLE
Is it possible to convert 3d tiles to obj format ? 

### ISSUE THREAD

**Issue by sau0409** [bertt/b3dm.tooling#3]
Is it possible to convert 3d tiles to obj format ?

**Comment by bertt** [comment]
not in this version, but could be added. Workaround is export to .glb and then to .obj using another tool

**Comment by sau0409** [comment]
@bertt So in 3d tiles there are multiple .b3dm files and this tool will convert each .b3dm file to a glb file. But how I will pack them into single Obj file ?

**Comment by bertt** [comment]
that would require a merge of glb's (not so easy). 

what's the goal you're trying to achieve? Maybe it's better to go to the original data that was used to create the 3D Tiles and process that.
